//! End-to-end validation of reference-guided 96-channel COSMIC signature
//! deconvolution against a synthetic dataset with a KNOWN ground truth.
//!
//! The fixtures in `test_data/cosmic_validation/` were generated by sampling
//! ~3,000 SNVs from the COSMIC v3.3 SBS4 (tobacco smoking) profile and placing
//! each mutation at a reference position whose trinucleotide context matches the
//! sampled channel. A correct pipeline must therefore recover SBS4 as the
//! dominant exposure with a near-perfect reconstruction.
//!
//! This exercises the full path: VCF parsing → reference FASTA loading →
//! trinucleotide-context spectrum construction → NNLS deconvolution against the
//! embedded COSMIC catalogue.

use std::path::Path;

use genomics_core::cosmic::compute_mutational_signatures_with_reference;
use genomics_core::parse_vcf;

/// Locate a fixture relative to the workspace root regardless of the crate the
/// test binary is launched from.
fn fixture(rel: &str) -> std::path::PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR"); // .../genomics_core
    Path::new(manifest).join("..").join(rel)
}

#[test]
fn recovers_known_sbs4_ground_truth_from_synthetic_sample() {
    let vcf = fixture("test_data/cosmic_validation/synthetic_sbs4.vcf");
    let fa = fixture("test_data/cosmic_validation/synthetic_ref.fa");

    let variants = parse_vcf(&vcf).expect("parse synthetic VCF");
    assert!(
        variants.len() > 2500,
        "expected ~3000 synthetic variants, got {}",
        variants.len()
    );

    let result = compute_mutational_signatures_with_reference(&variants, &fa)
        .expect("reference-guided COSMIC analysis");

    // The reference-guided path must have been taken.
    assert_eq!(result.method, "96-channel NNLS (COSMIC v3.3)");
    let sbs96 = result.sbs96.as_ref().expect("96-channel spectrum present");
    assert_eq!(
        sbs96.skipped_no_context, 0,
        "every synthetic variant should resolve a trinucleotide context"
    );

    // Reconstruction must be essentially perfect for a pure single-signature sample.
    let cosine = result.reconstruction_cosine.expect("cosine present");
    assert!(cosine > 0.99, "reconstruction cosine too low: {cosine}");

    // Ground truth: SBS4 dominates.
    assert!(!result.cosmic_exposures.is_empty(), "no exposures recovered");
    let top = &result.cosmic_exposures[0];
    assert_eq!(top.signature, "SBS4", "expected SBS4 as dominant signature");
    assert!(top.weight > 0.9, "SBS4 weight too low: {}", top.weight);

    // The tobacco process flag must derive from the recovered signature.
    assert!(result.tobacco_signature, "tobacco flag should be set for SBS4");
}
