//! Data-Independent Acquisition (DIA) proteomics — spectral library matching.
//!
//! DIA acquires MS2 spectra from all co-eluting precursors simultaneously
//! within wide isolation windows. Unlike DDA, there is no single-peptide
//! precursor selection; every fragment ion from every co-eluting peptide
//! appears in every MS2 scan.
//!
//! # Algorithm
//! For each library entry (peptide, charge, RT):
//!   1. Find MS2 scans whose isolation window covers the library precursor m/z.
//!   2. Extract the intensity at each library fragment ion m/z across those scans.
//!   3. Build a fragment ion chromatogram (XIC) for each library fragment.
//!   4. Score the library spectrum against the summed extracted intensities using
//!      the normalised dot product (spectral angle / library dot score).
//!   5. Apply an RT deviation penalty: score × exp(−(ΔRTT / σ_rt)²).
//!
//! Only library entries with a dot score ≥ `MIN_DOT_SCORE` and at least
//! `MIN_FRAGMENTS` matching fragments are reported.
//!
//! # References
//! * Röst HL et al. (2014) OpenSWATH enables automated, targeted analysis of
//!   data-independent acquisition MS data. Nature Biotechnology 32:219–223.
//! * Gessulat S et al. (2019) Prosit: proteome-wide prediction of peptide
//!   tandem mass spectra by deep learning. Nature Methods 16:509–518.

use serde::{Deserialize, Serialize};

use crate::types::{Spectrum, PROTON};

/// Minimum normalised dot-product score to report a DIA match.
pub const MIN_DOT_SCORE: f32 = 0.5;

/// Minimum number of matching library fragments required.
pub const MIN_FRAGMENTS: usize = 3;

/// Default RT window (seconds) for fragment XIC extraction.
pub const RT_WINDOW_SEC: f32 = 60.0;

/// Default RT tolerance σ for Gaussian penalty.
pub const RT_SIGMA_SEC: f32 = 30.0;

/// One entry in a spectral library.
///
/// Library entries are typically generated by a tool like Prosit or from
/// empirical DDA searches, then stored as a flat list for DIA matching.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LibraryEntry {
    /// Peptide sequence (unmodified; modifications encoded in `mod_mass`).
    pub sequence: String,
    /// Protein name.
    pub protein: String,
    /// Precursor m/z (observed or theoretical).
    pub precursor_mz: f32,
    /// Precursor charge.
    pub charge: u8,
    /// Predicted or empirical retention time in seconds.
    pub rt: f32,
    /// Up to 12 library fragment ions: `(fragment_mz, relative_intensity)`.
    /// Intensities are normalised to the base peak (max = 1.0).
    pub fragments: Vec<(f32, f32)>,
    /// Protein-level decoy flag.
    pub is_decoy: bool,
}

/// DIA peptide-spectrum match result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiaPsm {
    pub sequence: String,
    pub protein: String,
    pub precursor_mz: f32,
    pub charge: u8,
    /// Best observed RT (centroid of the XIC peak).
    pub rt: f32,
    /// Normalised dot-product score (0–1).
    pub dot_score: f32,
    /// Number of matching library fragments.
    pub n_fragments: usize,
    /// RT deviation from library prediction in seconds.
    pub rt_delta: f32,
    pub is_decoy: bool,
    /// Q-value (set by `assign_dia_qvalues`).
    pub q_value: f64,
}

/// Score a spectral library against DIA spectra.
///
/// # Arguments
/// - `library`: spectral library entries (target + decoy).
/// - `spectra`: all MS2 spectra from the DIA run (sorted by RT).
/// - `frag_tol_ppm`: fragment ion extraction tolerance.
/// - `rt_window`: ± seconds around the library RT for XIC extraction.
///
/// # Returns
/// All `DiaPsm` entries with dot score ≥ `MIN_DOT_SCORE` and ≥ `MIN_FRAGMENTS`
/// matching fragments, sorted by dot score descending.
pub fn score_library_against_dia(
    library: &[LibraryEntry],
    spectra: &[Spectrum],
    frag_tol_ppm: f64,
    rt_window: f32,
) -> Vec<DiaPsm> {
    // Pre-index MS2 spectra by RT for fast range lookups.
    let ms2: Vec<&Spectrum> = spectra.iter().filter(|s| s.ms_level == 2).collect();

    let mut results: Vec<DiaPsm> = library
        .iter()
        .filter_map(|entry| {
            if entry.fragments.is_empty() {
                return None;
            }

            // Collect MS2 scans within RT window and covering the precursor m/z.
            let rt_lo = entry.rt - rt_window;
            let rt_hi = entry.rt + rt_window;

            let candidate_scans: Vec<&Spectrum> = ms2
                .iter()
                .copied()
                .filter(|s| s.rt >= rt_lo && s.rt <= rt_hi)
                .collect();

            if candidate_scans.is_empty() {
                return None;
            }

            // Extract XIC for each library fragment across all candidate scans.
            // xic_sum[i] = summed intensity for library fragment i.
            let mut xic_sum: Vec<f32> = vec![0.0; entry.fragments.len()];
            let mut best_rt = entry.rt;
            let mut best_scan_intensity = 0.0f32;

            for scan in &candidate_scans {
                let mut scan_sum = 0.0f32;
                for (fi, &(frag_mz, _lib_int)) in entry.fragments.iter().enumerate() {
                    if let Some(int) = extract_intensity(scan, frag_mz, frag_tol_ppm) {
                        xic_sum[fi] += int;
                        scan_sum += int;
                    }
                }
                if scan_sum > best_scan_intensity {
                    best_scan_intensity = scan_sum;
                    best_rt = scan.rt;
                }
            }

            // Count matching fragments (at least one non-zero XIC value).
            let n_fragments = xic_sum.iter().filter(|&&v| v > 0.0).count();
            if n_fragments < MIN_FRAGMENTS {
                return None;
            }

            // Normalised dot product between library intensities and XIC sums.
            let dot = normalised_dot(&entry.fragments, &xic_sum);
            if dot < MIN_DOT_SCORE {
                return None;
            }

            // Gaussian RT penalty.
            let rt_delta = (best_rt - entry.rt).abs();
            let rt_penalty = (-(rt_delta / RT_SIGMA_SEC).powi(2)).exp().max(0.01);
            let final_score = dot * rt_penalty;

            Some(DiaPsm {
                sequence: entry.sequence.clone(),
                protein: entry.protein.clone(),
                precursor_mz: entry.precursor_mz,
                charge: entry.charge,
                rt: best_rt,
                dot_score: final_score,
                n_fragments,
                rt_delta,
                is_decoy: entry.is_decoy,
                q_value: 1.0,
            })
        })
        .collect();

    results.sort_unstable_by(|a, b| {
        b.dot_score
            .partial_cmp(&a.dot_score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    results
}

/// Extract the highest intensity at a target m/z within the given PPM tolerance.
#[inline]
fn extract_intensity(spectrum: &Spectrum, target_mz: f32, tol_ppm: f64) -> Option<f32> {
    let tol = (target_mz as f64 * tol_ppm / 1e6) as f32;
    let lo = target_mz - tol;
    let hi = target_mz + tol;
    let start = spectrum.mz.partition_point(|&x| x < lo);
    spectrum.mz[start..]
        .iter()
        .zip(spectrum.intensity[start..].iter())
        .take_while(|(&mz, _)| mz <= hi)
        .map(|(_, &int)| int)
        .reduce(f32::max)
}

/// Normalised dot product (cosine similarity) between library and observed intensities.
///
/// Library fragment intensities are taken from `fragments[i].1`; observed
/// intensities come from `xic[i]`. Both vectors are L2-normalised before
/// computing the dot product.
fn normalised_dot(fragments: &[(f32, f32)], xic: &[f32]) -> f32 {
    debug_assert_eq!(fragments.len(), xic.len());

    let lib_norm: f32 = fragments.iter().map(|(_, i)| i * i).sum::<f32>().sqrt();
    let obs_norm: f32 = xic.iter().map(|&v| v * v).sum::<f32>().sqrt();

    if lib_norm < 1e-9 || obs_norm < 1e-9 {
        return 0.0;
    }

    fragments
        .iter()
        .zip(xic.iter())
        .map(|((_, li), &oi)| (li / lib_norm) * (oi / obs_norm))
        .sum::<f32>()
        .clamp(0.0, 1.0)
}

/// Assign target-decoy q-values to DIA PSMs (Laplace-corrected, sorted by score).
pub fn assign_dia_qvalues(psms: &mut [DiaPsm]) {
    psms.sort_unstable_by(|a, b| {
        b.dot_score
            .partial_cmp(&a.dot_score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    let mut n_target = 0u64;
    let mut n_decoy = 0u64;
    let mut fdr_values: Vec<f64> = Vec::with_capacity(psms.len());

    for psm in psms.iter() {
        if psm.is_decoy {
            n_decoy += 1;
        } else {
            n_target += 1;
        }
        fdr_values.push(((n_decoy + 1) as f64 / n_target.max(1) as f64).min(1.0));
    }

    // Backward rolling minimum for monotone q-values.
    let mut min_fdr = 1.0f64;
    let mut q_vals: Vec<f64> = fdr_values
        .iter()
        .rev()
        .map(|&f| {
            min_fdr = min_fdr.min(f);
            min_fdr
        })
        .collect();
    q_vals.reverse();

    for (psm, q) in psms.iter_mut().zip(q_vals) {
        psm.q_value = q;
    }
}

/// Build a minimal in-memory spectral library from DDA PSMs.
///
/// Converts confident DDA PSMs into library entries using theoretical b/y ions
/// as fragment m/z values. This allows a DDA-first + DIA-validation workflow
/// without requiring an external library tool like Prosit.
pub fn build_library_from_psms(
    psms: &[crate::types::Psm],
    fdr_threshold: f64,
) -> Vec<LibraryEntry> {
    use crate::score::{b_ions, y_ions};

    psms.iter()
        .filter(|p| !p.is_decoy && p.q_value <= fdr_threshold)
        .map(|psm| {
            let b = b_ions(psm.peptide.as_bytes());
            let y = y_ions(psm.peptide.as_bytes());

            // Take top-6 b and top-6 y ions (most informative).
            let mut frags: Vec<(f32, f32)> = b
                .iter()
                .take(6)
                .map(|&m| (m as f32, 0.5))
                .chain(y.iter().take(6).map(|&m| (m as f32, 1.0)))
                .collect();

            // Normalise to base peak = 1.0.
            let max_int = frags.iter().map(|(_, i)| *i).fold(0.0f32, f32::max);
            if max_int > 0.0 {
                frags.iter_mut().for_each(|(_, i)| *i /= max_int);
            }

            let precursor_mz = ((psm.peptide.len() as f64 * 111.0 + PROTON * psm.charge as f64)
                / psm.charge as f64) as f32;

            LibraryEntry {
                sequence: psm.peptide.clone(),
                protein: psm.protein.clone(),
                precursor_mz,
                charge: psm.charge,
                rt: psm.rt,
                fragments: frags,
                is_decoy: false,
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_spectrum(rt: f32, peaks: &[(f32, f32)]) -> Spectrum {
        let mut pairs: Vec<(f32, f32)> = peaks.to_vec();
        pairs.sort_unstable_by(|a, b| a.0.partial_cmp(&b.0).unwrap());
        Spectrum {
            scan: 1,
            ms_level: 2,
            rt,
            precursor_mz: 500.0,
            precursor_z: 0,
            mz: pairs.iter().map(|p| p.0).collect(),
            intensity: pairs.iter().map(|p| p.1).collect(),
        }
    }

    fn make_entry(frags: &[(f32, f32)]) -> LibraryEntry {
        LibraryEntry {
            sequence: "PEPTIDE".into(),
            protein: "PROT".into(),
            precursor_mz: 450.0,
            charge: 2,
            rt: 30.0,
            fragments: frags.to_vec(),
            is_decoy: false,
        }
    }

    #[test]
    fn perfect_match_scores_high() {
        let frags = vec![(100.0f32, 1.0), (200.0, 0.8), (300.0, 0.5)];
        let spectrum = make_spectrum(
            30.0,
            &[(100.0, 1.0), (200.0, 0.8), (300.0, 0.5), (999.0, 0.01)],
        );
        let entry = make_entry(&frags);
        let results = score_library_against_dia(&[entry], &[spectrum], 20.0, 60.0);
        assert!(!results.is_empty(), "should match");
        assert!(results[0].dot_score > 0.9, "score={}", results[0].dot_score);
        assert_eq!(results[0].n_fragments, 3);
    }

    #[test]
    fn no_match_below_threshold() {
        let frags = vec![(100.0f32, 1.0), (200.0, 0.8), (300.0, 0.5)];
        // Spectrum has peaks at completely different positions.
        let spectrum = make_spectrum(30.0, &[(500.0, 1.0), (600.0, 0.8), (700.0, 0.5)]);
        let entry = make_entry(&frags);
        let results = score_library_against_dia(&[entry], &[spectrum], 20.0, 60.0);
        assert!(results.is_empty(), "should not match disjoint peaks");
    }

    #[test]
    fn out_of_rt_window_not_matched() {
        let frags = vec![(100.0f32, 1.0), (200.0, 0.8), (300.0, 0.5)];
        // Spectrum at RT=200s, library expects RT=30s, window=60s → no match.
        let spectrum = make_spectrum(200.0, &[(100.0, 1.0), (200.0, 0.8), (300.0, 0.5)]);
        let entry = make_entry(&frags);
        let results = score_library_against_dia(&[entry], &[spectrum], 20.0, 60.0);
        assert!(results.is_empty(), "RT too far outside window");
    }

    #[test]
    fn dia_qvalues_monotone() {
        let mut psms = vec![
            DiaPsm {
                sequence: "PEPTIDE".into(),
                protein: "P1".into(),
                precursor_mz: 100.0,
                charge: 2,
                rt: 30.0,
                dot_score: 0.9,
                n_fragments: 5,
                rt_delta: 2.0,
                is_decoy: false,
                q_value: 1.0,
            },
            DiaPsm {
                sequence: "DECOY".into(),
                protein: "D1".into(),
                precursor_mz: 101.0,
                charge: 2,
                rt: 30.0,
                dot_score: 0.6,
                n_fragments: 3,
                rt_delta: 5.0,
                is_decoy: true,
                q_value: 1.0,
            },
        ];
        assign_dia_qvalues(&mut psms);
        // Q-values should be non-decreasing after sorting by score desc.
        for w in psms.windows(2) {
            assert!(w[0].q_value <= w[1].q_value || w[0].dot_score >= w[1].dot_score);
        }
    }

    #[test]
    fn normalised_dot_identical() {
        let frags = vec![(100.0f32, 1.0), (200.0, 0.5)];
        let xic = vec![1.0f32, 0.5];
        let score = normalised_dot(&frags, &xic);
        assert!(
            (score - 1.0).abs() < 1e-5,
            "identical → dot=1.0, got {score}"
        );
    }
}
