//! FASTA protein database parser and in-silico tryptic digest.
//!
//! Generates target peptides by trypsin cleavage (K/R | not P) with 0–2
//! missed cleavages. Decoys are generated by sequence reversal (keeping the
//! last amino acid in place so the K/R cleavage site is preserved, following
//! the Prosit/Sage convention).

use rayon::prelude::*;

use crate::types::{aa_mass, Peptide, WATER};

/// Parsed protein entry.
pub struct Protein {
    pub header: String,
    pub sequence: Vec<u8>,
}

/// Parse a FASTA byte slice into protein entries.
pub fn parse_fasta(data: &[u8]) -> Vec<Protein> {
    let mut proteins: Vec<Protein> = Vec::new();
    let mut header = String::new();
    let mut seq: Vec<u8> = Vec::new();

    for line in data.split(|&b| b == b'\n') {
        let line = trim_bytes(line);
        if line.is_empty() {
            continue;
        }
        if line[0] == b'>' {
            if !header.is_empty() && !seq.is_empty() {
                proteins.push(Protein {
                    header: header.clone(),
                    sequence: seq.clone(),
                });
            }
            header = String::from_utf8_lossy(&line[1..]).into_owned();
            seq.clear();
        } else {
            seq.extend_from_slice(line);
        }
    }
    if !header.is_empty() && !seq.is_empty() {
        proteins.push(Protein {
            header,
            sequence: seq,
        });
    }
    proteins
}

/// Generate target + decoy peptides from a protein list in parallel.
///
/// Each protein is digested independently via rayon then merged. Decoy
/// sequences are reversed (last AA fixed) to preserve the K/R tryptic
/// terminus — same convention as Sage / Prosit. Parameters:
/// - `max_missed`: 0–2 missed cleavages
/// - `min_len` / `max_len`: peptide length filter
pub fn digest(
    proteins: &[Protein],
    max_missed: u8,
    min_len: usize,
    max_len: usize,
) -> Vec<Peptide> {
    proteins
        .par_iter()
        .enumerate()
        .flat_map(|(prot_idx, prot)| {
            let sites = cleavage_sites(&prot.sequence);
            let segments = sites_to_segments(&sites, prot.sequence.len());
            let prot_name = first_word(&prot.header);
            let mut local: Vec<Peptide> = Vec::new();

            for mc in 0..=(max_missed as usize) {
                for i in 0..segments.len() {
                    let end_seg = i + mc;
                    if end_seg >= segments.len() {
                        break;
                    }
                    let seq_bytes = &prot.sequence[segments[i].0..segments[end_seg].1];
                    if seq_bytes.len() < min_len || seq_bytes.len() > max_len {
                        continue;
                    }
                    let mass = peptide_mass(seq_bytes);
                    if mass <= 0.0 {
                        continue;
                    }
                    let seq_str = String::from_utf8_lossy(seq_bytes).into_owned();

                    local.push(Peptide {
                        sequence: seq_str.clone(),
                        mass,
                        protein_idx: prot_idx as u32,
                        is_decoy: false,
                        missed_cleavages: mc as u8,
                        modifications: vec![],
                    });

                    // Decoy: reversed sequence (last AA kept in place).
                    let decoy_seq = reverse_peptide(seq_bytes);
                    let decoy_str = String::from_utf8_lossy(&decoy_seq).into_owned();
                    local.push(Peptide {
                        sequence: format!("DECOY_{prot_name}_{decoy_str}"),
                        mass,
                        protein_idx: prot_idx as u32,
                        is_decoy: true,
                        missed_cleavages: mc as u8,
                        modifications: vec![],
                    });
                }
            }
            local
        })
        .collect()
}

/// Compute the monoisotopic neutral mass of a peptide.
#[inline]
pub fn peptide_mass(seq: &[u8]) -> f64 {
    let mut mass = WATER;
    for &aa in seq {
        let m = aa_mass(aa.to_ascii_uppercase());
        if m == 0.0 {
            return 0.0; // unknown residue → skip
        }
        mass += m;
    }
    mass
}

/// Find trypsin cleavage sites (after K/R not followed by P).
fn cleavage_sites(seq: &[u8]) -> Vec<usize> {
    let mut sites: Vec<usize> = vec![0];
    for i in 0..seq.len().saturating_sub(1) {
        let aa = seq[i].to_ascii_uppercase();
        let next = seq[i + 1].to_ascii_uppercase();
        if (aa == b'K' || aa == b'R') && next != b'P' {
            sites.push(i + 1);
        }
    }
    sites.push(seq.len());
    sites
}

/// Convert cleavage site positions to (start, end) segments.
fn sites_to_segments(sites: &[usize], seq_len: usize) -> Vec<(usize, usize)> {
    let mut segs: Vec<(usize, usize)> = Vec::new();
    for window in sites.windows(2) {
        let start = window[0];
        let end = window[1].min(seq_len);
        if start < end {
            segs.push((start, end));
        }
    }
    segs
}

/// Reverse peptide keeping last residue in place (preserves K/R cleavage site).
fn reverse_peptide(seq: &[u8]) -> Vec<u8> {
    if seq.len() <= 1 {
        return seq.to_vec();
    }
    let mut rev: Vec<u8> = seq[..seq.len() - 1].iter().rev().copied().collect();
    rev.push(*seq.last().unwrap());
    rev
}

fn first_word(s: &str) -> &str {
    s.split_whitespace().next().unwrap_or(s)
}

fn trim_bytes(b: &[u8]) -> &[u8] {
    let start = b
        .iter()
        .position(|&x| x != b' ' && x != b'\r' && x != b'\t')
        .unwrap_or(b.len());
    let end = b
        .iter()
        .rposition(|&x| x != b' ' && x != b'\r' && x != b'\t')
        .map(|i| i + 1)
        .unwrap_or(0);
    if start >= end {
        &[]
    } else {
        &b[start..end]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TINY_FASTA: &[u8] = b">sp|P12345|PROT_HUMAN Example protein\nMEPTIDEKPEPTIDER\n>sp|P99999|ANOTHER\nACDEFGHIKLMNPQRSTVWY\n";

    #[test]
    fn parse_two_proteins() {
        let prots = parse_fasta(TINY_FASTA);
        assert_eq!(prots.len(), 2);
        assert_eq!(prots[0].sequence, b"MEPTIDEKPEPTIDER");
    }

    #[test]
    fn digest_produces_peptides() {
        let prots = parse_fasta(TINY_FASTA);
        let peps = digest(&prots, 1, 6, 50);
        // Should contain targets and decoys
        assert!(!peps.is_empty());
        let targets: Vec<_> = peps.iter().filter(|p| !p.is_decoy).collect();
        let decoys: Vec<_> = peps.iter().filter(|p| p.is_decoy).collect();
        assert_eq!(targets.len(), decoys.len());
    }

    #[test]
    fn peptide_mass_basic() {
        // Glycine dimer GG: 57.021 + 57.021 + 18.011 = 132.053
        let mass = peptide_mass(b"GG");
        assert!((mass - 132.053).abs() < 0.01, "GG mass: {mass}");
    }
}
