//! Phosphoproteomics: variable modification search for phosphorylation.
//!
//! Generates all possible phosphorylated forms of tryptic peptides by placing
//! the +79.966 Da HPO₃ modification on every combination of serine (S),
//! threonine (T), and tyrosine (Y) residues up to `max_sites`.
//!
//! # Combinatorial budget
//! For a peptide with `n` S/T/Y residues and `max_sites = 3`:
//!   C(n,1) + C(n,2) + C(n,3) variants.
//! A peptide with 5 S/T/Y sites produces at most 25 variants — well within
//! the budget for typical tryptic peptides.
//!
//! # Integration
//! Modified peptides are added to the same `PeptideIndex` as their unmodified
//! parents. Because their mass is shifted by N × 79.966 Da, they land in
//! different precursor bins and are found by the standard fragment-vote search
//! without any algorithmic changes.

use crate::types::{Modification, Peptide};

/// Monoisotopic mass of the phospho group (HPO₃).
pub const PHOSPHO_MASS: f64 = 79.966_330_9;

/// Maximum phosphorylation sites per peptide (default; configurable via CLI).
pub const DEFAULT_MAX_PHOSPHO_SITES: usize = 2;

/// Amino acids eligible for phosphorylation.
const PHOSPHO_RESIDUES: [u8; 3] = [b'S', b'T', b'Y'];

/// Generate all phosphorylated variants of a peptide up to `max_sites` phospho groups.
///
/// Returns an empty slice if the peptide contains no S/T/Y residues.
/// The original (unmodified) peptide is **not** included in the output —
/// it is already in the main peptide list.
pub fn phospho_variants(peptide: &Peptide, max_sites: usize) -> Vec<Peptide> {
    if max_sites == 0 {
        return vec![];
    }

    // Find positions of phosphorylatable residues in the raw sequence.
    // Skip decoys — phospho decoys are generated by the same combinations.
    let sty_positions: Vec<usize> = peptide
        .sequence
        .bytes()
        .enumerate()
        .filter(|(_, aa)| PHOSPHO_RESIDUES.contains(aa))
        .map(|(i, _)| i)
        .collect();

    if sty_positions.is_empty() {
        return vec![];
    }

    let n = sty_positions.len();
    let k_max = max_sites.min(n);
    let mut variants: Vec<Peptide> = Vec::new();

    // Enumerate all combinations of 1..=k_max S/T/Y positions.
    for k in 1..=k_max {
        for combo in combinations(&sty_positions, k) {
            let mod_mass: f64 = k as f64 * PHOSPHO_MASS;
            let modifications: Vec<Modification> = combo
                .iter()
                .map(|&pos| Modification {
                    position: pos,
                    mass_delta: PHOSPHO_MASS,
                    label: "Phospho",
                })
                .collect();

            variants.push(Peptide {
                sequence: peptide.sequence.clone(),
                mass: peptide.mass + mod_mass,
                protein_idx: peptide.protein_idx,
                is_decoy: peptide.is_decoy,
                missed_cleavages: peptide.missed_cleavages,
                modifications,
            });
        }
    }

    variants
}

/// Generate phospho variants for an entire peptide list and append them in-place.
///
/// Only unmodified peptides (modifications.is_empty()) are expanded —
/// prevents combinatorial explosion on already-modified forms.
pub fn expand_with_phospho(peptides: &mut Vec<Peptide>, max_sites: usize) {
    if max_sites == 0 {
        return;
    }
    // Collect variants first (can't borrow mutably and iterate simultaneously).
    let extra: Vec<Peptide> = peptides
        .iter()
        .filter(|p| p.modifications.is_empty())
        .flat_map(|p| phospho_variants(p, max_sites))
        .collect();

    peptides.extend(extra);
}

/// Enumerate k-combinations from a slice of positions.
fn combinations(positions: &[usize], k: usize) -> Vec<Vec<usize>> {
    if k == 0 {
        return vec![vec![]];
    }
    if positions.len() < k {
        return vec![];
    }
    let mut result = Vec::new();
    let mut indices: Vec<usize> = (0..k).collect();
    let n = positions.len();

    loop {
        result.push(indices.iter().map(|&i| positions[i]).collect());
        // Advance to next combination (lexicographic order).
        let mut i = k;
        loop {
            if i == 0 {
                return result;
            }
            i -= 1;
            if indices[i] != i + n - k {
                break;
            }
        }
        indices[i] += 1;
        for j in (i + 1)..k {
            indices[j] = indices[j - 1] + 1;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fasta::peptide_mass;

    fn base_peptide(seq: &str) -> Peptide {
        Peptide {
            sequence: seq.into(),
            mass: peptide_mass(seq.as_bytes()),
            protein_idx: 0,
            is_decoy: false,
            missed_cleavages: 0,
            modifications: vec![],
        }
    }

    #[test]
    fn no_sty_no_variants() {
        let p = base_peptide("AAAGGGR");
        assert!(phospho_variants(&p, 2).is_empty());
    }

    #[test]
    fn single_s_one_variant() {
        // AASAAAK has exactly one S at position 2 → 1 phospho variant.
        let p = base_peptide("AASAAAK");
        let variants = phospho_variants(&p, 2);
        assert_eq!(variants.len(), 1);
        assert!((variants[0].mass - p.mass - PHOSPHO_MASS).abs() < 1e-6);
        assert_eq!(variants[0].modifications.len(), 1);
        assert_eq!(variants[0].modifications[0].label, "Phospho");
    }

    #[test]
    fn two_sty_up_to_two_sites() {
        // STY contains S at 0 and T at 1 → C(2,1)+C(2,2) = 3 variants
        let p = base_peptide("STAAAK");
        let variants = phospho_variants(&p, 2);
        assert_eq!(variants.len(), 3, "S+T with max_sites=2 → 3 variants");
    }

    #[test]
    fn three_sty_max_two_sites() {
        // SSS → C(3,1)+C(3,2) = 3+3 = 6 variants
        let p = base_peptide("SSSAAAK");
        let variants = phospho_variants(&p, 2);
        assert_eq!(variants.len(), 6);
    }

    #[test]
    fn combinations_correct() {
        let c = combinations(&[0, 1, 2], 2);
        assert_eq!(c.len(), 3);
        assert!(c.contains(&vec![0, 1]));
        assert!(c.contains(&vec![0, 2]));
        assert!(c.contains(&vec![1, 2]));
    }

    #[test]
    fn expand_with_phospho_appends() {
        // AAAGGGR: no S/T/Y → 0 variants.
        // STAAAK:  S at 0, T at 1 → C(2,1)+C(2,2) = 3 variants.
        let mut peps = vec![base_peptide("AAAGGGR"), base_peptide("STAAAK")];
        let n_before = peps.len();
        expand_with_phospho(&mut peps, 2);
        assert_eq!(peps.len(), n_before + 3);
    }
}
