"""
multiqc_multiomics — MultiQC module for Multiomics reports.

Multiomics produces a MultiQC-compatible JSON file named
``multiqc_multiomics.json`` in its output directory.  This module reads that
file and adds the following sections to every MultiQC report that is run
against the same output directory:

* **General Statistics** table — variant counts, Ti/Tv ratio, expressed
  genes, global methylation percentage, CpG islands detected.
* **Variant density per chromosome** — stacked bar chart showing SNPs vs
  indels broken down by chromosome (from ``multiomics_genomics.per_chrom``).
* **Methylation per chromosome** — bar chart showing mean methylation % by
  chromosome (from ``multiomics_epigenomics.per_chrom_methylation``).
* **Biological insights** — colour-coded HTML list of plain-English findings
  generated by the Multiomics insight engine
  (from ``multiomics_integration.insights``).
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional

from multiqc.base_module import BaseMultiqcModule, ModuleNoSamplesFound
from multiqc.plots import bargraph, table

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Entry-point shim — called by setup.py ``multiqc.cli_options`` but we have
# nothing extra to register, so this is a no-op.
# ---------------------------------------------------------------------------


def cli_options(ctx: Any) -> None:  # noqa: ANN001
    """No extra CLI options required for this plugin."""
    pass


# ---------------------------------------------------------------------------
# Colour mapping for insight severity levels produced by the Rust tool.
# ---------------------------------------------------------------------------

_LEVEL_COLOURS: Dict[str, str] = {
    "INFO": "#28a745",
    "WARN": "#ffc107",
    "CRIT": "#dc3545",
}

_LEVEL_LABELS: Dict[str, str] = {
    "INFO": "Info",
    "WARN": "Warning",
    "CRIT": "Critical",
}

# ---------------------------------------------------------------------------
# Module class
# ---------------------------------------------------------------------------


class MultiqcModule(BaseMultiqcModule):
    """MultiQC module for Multiomics integrated multi-omics reports."""

    def __init__(self) -> None:
        super().__init__(
            name="Multiomics",
            anchor="multiomics",
            href="https://github.com/diladeniz/multiomics",
            info=(
                "Parallel multi-omics analysis integrating genomics (VCF), "
                "transcriptomics (expression matrix), and epigenomics (BED methylation) "
                "into a single integrated report."
            ),
            doi="10.5281/zenodo.placeholder",
            # Tell MultiQC which filename pattern to search for.
            # The search_files() call below uses the key ``multiomics``.
        )

        # Accumulate data across potentially multiple samples / run directories.
        self.multiomics_general_stats: Dict[str, Dict[str, Any]] = {}
        self.multiomics_genomics: Dict[str, Any] = {}
        self.multiomics_epigenomics: Dict[str, Any] = {}
        self.multiomics_integration: Dict[str, Any] = {}

        # Search for all ``multiqc_multiomics.json`` files in the analysis paths.
        for f in self.find_log_files("multiomics", filecontents=True, filehandles=False):
            self._parse_multiomics_json(f)

        # Filter to only samples that passed ignore/rename rules.
        self.multiomics_general_stats = self.ignore_samples(self.multiomics_general_stats)

        if not self.multiomics_general_stats:
            raise ModuleNoSamplesFound

        log.debug("Found %d Multiomics report(s)", len(self.multiomics_general_stats))

        # Write parsed data to disk so it can be included in multiqc_data/.
        self.write_data_file(self.multiomics_general_stats, "multiqc_multiomics_general")

        # Add content to the report.
        self._add_general_stats()
        self._add_variant_density_section()
        self._add_methylation_section()
        self._add_insights_section()

    # ------------------------------------------------------------------
    # Parsing
    # ------------------------------------------------------------------

    def _parse_multiomics_json(self, log_file: Dict[str, Any]) -> None:
        """Parse a single ``multiqc_multiomics.json`` file."""
        try:
            data: Dict[str, Any] = json.loads(log_file["f"])
        except json.JSONDecodeError as exc:
            log.warning(
                "Could not parse Multiomics JSON '%s': %s",
                log_file["fn"],
                exc,
            )
            return

        # Derive a sample name from the directory the file lives in, falling
        # back to the filename if the directory name is uninformative.
        sample_name: str = self.clean_s_name(log_file["s_name"], log_file)

        # ---- General statistics ----------------------------------------
        general_data: Dict[str, Any] = {}

        # Primary source: report_general_stats_data (list of {sample: stats})
        gs_list: List[Dict[str, Any]] = data.get("report_general_stats_data", [])
        for entry in gs_list:
            for _s, stats in entry.items():
                general_data = stats
                break
            if general_data:
                break

        # Fallback: pull directly from the modality sections.
        if not general_data:
            gen = data.get("multiomics_genomics", {})
            epi = data.get("multiomics_epigenomics", {})
            trans = data.get("multiomics_transcriptomics", {})
            general_data = {
                "total_variants": gen.get("total_variants", 0),
                "snp_count": gen.get("snp_count", 0),
                "indel_count": gen.get("indel_count", 0),
                "titv_ratio": gen.get("titv_ratio", 0.0),
                "total_genes": trans.get("total_genes", 0),
                "expressed_genes": trans.get("expressed_genes", 0),
                "total_sites": epi.get("total_sites", 0),
                "global_methylation_pct": epi.get("global_methylation_pct", 0.0),
                "cpg_islands_detected": epi.get("cpg_islands_detected", 0),
            }

        self.multiomics_general_stats[sample_name] = general_data

        # ---- Per-modality sections ------------------------------------
        self.multiomics_genomics[sample_name] = data.get("multiomics_genomics", {})
        self.multiomics_epigenomics[sample_name] = data.get("multiomics_epigenomics", {})
        self.multiomics_integration[sample_name] = data.get("multiomics_integration", {})

        self.add_data_source(log_file, sample_name)

    # ------------------------------------------------------------------
    # General Statistics table
    # ------------------------------------------------------------------

    def _add_general_stats(self) -> None:
        """Add Multiomics metrics to the MultiQC General Statistics table."""

        headers: Dict[str, Dict[str, Any]] = {
            "total_variants": {
                "title": "Variants",
                "description": "Total number of variants (SNPs + indels) detected in the VCF.",
                "scale": "Blues",
                "format": "{:,.0f}",
                "shared_key": "variant_count",
            },
            "titv_ratio": {
                "title": "Ti/Tv",
                "description": (
                    "Transition / transversion ratio. "
                    "Expected ~2.0–2.1 for whole-genome sequencing."
                ),
                "scale": "RdYlGn",
                "format": "{:.2f}",
                "min": 0,
                "max": 4,
            },
            "expressed_genes": {
                "title": "Expr. Genes",
                "description": "Number of genes with TPM ≥ 1 (expressed).",
                "scale": "Greens",
                "format": "{:,.0f}",
                "shared_key": "gene_count",
            },
            "global_methylation_pct": {
                "title": "Methylation %",
                "description": "Global CpG methylation percentage across all analysed sites.",
                "scale": "Oranges",
                "format": "{:.1f}",
                "suffix": "%",
                "min": 0,
                "max": 100,
            },
            "cpg_islands_detected": {
                "title": "CpG Islands",
                "description": "Number of CpG islands detected in the methylation BED file.",
                "scale": "Purples",
                "format": "{:,.0f}",
            },
        }

        self.general_stats_addcols(self.multiomics_general_stats, headers)

    # ------------------------------------------------------------------
    # Per-chromosome variant density bar chart
    # ------------------------------------------------------------------

    def _add_variant_density_section(self) -> None:
        """Add a stacked bar chart of per-chromosome variant counts."""

        # Collect data: {sample: {chrom: {snps: N, indels: N}}}
        plot_data: List[Dict[str, Dict[str, int]]] = [{}, {}]  # [SNPs dict, indels dict]
        any_data = False

        for sample, gdata in self.multiomics_genomics.items():
            per_chrom: Dict[str, Any] = gdata.get("per_chrom", {})
            if not per_chrom:
                continue
            any_data = True

            snp_row: Dict[str, int] = {}
            indel_row: Dict[str, int] = {}

            for chrom, stats in sorted(
                per_chrom.items(),
                key=lambda kv: _chrom_sort_key(kv[0]),
            ):
                snp_row[chrom] = int(stats.get("snps", 0))
                indel_row[chrom] = int(stats.get("indels", 0))

            # Bargraph uses {sample_name: {category: value}} structure.
            plot_data[0][sample] = snp_row
            plot_data[1][sample] = indel_row

        if not any_data:
            return

        cats: List[Dict[str, Dict[str, str]]] = [
            {chrom: {"name": chrom, "color": "#4e79a7"} for chrom in next(iter(plot_data[0].values()), {})},
            {chrom: {"name": chrom, "color": "#f28e2b"} for chrom in next(iter(plot_data[1].values()), {})},
        ]

        # Flatten into a single dict per sample with combined keys for stacked display.
        flat: Dict[str, Dict[str, int]] = {}
        for sample in self.multiomics_genomics:
            row: Dict[str, int] = {}
            for chrom, n in plot_data[0].get(sample, {}).items():
                row[f"{chrom} SNPs"] = n
            for chrom, n in plot_data[1].get(sample, {}).items():
                row[f"{chrom} Indels"] = n
            if row:
                flat[sample] = row

        # Build ordered category list alternating SNPs/Indels per chrom.
        all_chroms = sorted(
            {c.removesuffix(" SNPs").removesuffix(" Indels") for c in next(iter(flat.values()), {})},
            key=_chrom_sort_key,
        )
        cats_flat: Dict[str, Dict[str, str]] = {}
        for chrom in all_chroms:
            cats_flat[f"{chrom} SNPs"] = {"name": f"{chrom} SNPs", "color": "#4e79a7"}
            cats_flat[f"{chrom} Indels"] = {"name": f"{chrom} Indels", "color": "#f28e2b"}

        pconfig = {
            "id": "multiomics_variant_density",
            "title": "Multiomics: Variant Density per Chromosome",
            "ylab": "Variant Count",
            "xlab": "Sample",
            "cpswitch": True,
            "cpswitch_c_active": False,
            "stacking": "normal",
        }

        self.add_section(
            name="Variant Density per Chromosome",
            anchor="multiomics-variant-density",
            description=(
                "Number of SNPs and indels detected per chromosome. "
                "Use the percentage switch to compare distributions across samples."
            ),
            plot=bargraph.plot(flat, cats_flat, pconfig),
        )

    # ------------------------------------------------------------------
    # Per-chromosome methylation bar chart
    # ------------------------------------------------------------------

    def _add_methylation_section(self) -> None:
        """Add a bar chart of mean methylation % per chromosome."""

        flat: Dict[str, Dict[str, float]] = {}
        any_data = False

        for sample, edata in self.multiomics_epigenomics.items():
            per_chrom: Dict[str, float] = edata.get("per_chrom_methylation", {})
            if not per_chrom:
                continue
            any_data = True
            flat[sample] = {
                chrom: round(float(pct), 2)
                for chrom, pct in sorted(
                    per_chrom.items(),
                    key=lambda kv: _chrom_sort_key(kv[0]),
                )
            }

        if not any_data:
            return

        all_chroms = sorted(
            {chrom for row in flat.values() for chrom in row},
            key=_chrom_sort_key,
        )

        cats: Dict[str, Dict[str, str]] = {
            chrom: {"name": chrom, "color": _methylation_colour(i, len(all_chroms))}
            for i, chrom in enumerate(all_chroms)
        }

        pconfig = {
            "id": "multiomics_methylation_per_chrom",
            "title": "Multiomics: Methylation per Chromosome",
            "ylab": "Mean Methylation %",
            "xlab": "Sample",
            "ymax": 100,
            "ymin": 0,
            "cpswitch": False,
            "tt_decimals": 1,
        }

        self.add_section(
            name="Methylation per Chromosome",
            anchor="multiomics-methylation",
            description=(
                "Mean CpG methylation percentage per chromosome. "
                "Pronounced deviations from the global average may indicate "
                "chromosomal-level epigenetic remodelling."
            ),
            plot=bargraph.plot(flat, cats, pconfig),
        )

    # ------------------------------------------------------------------
    # Biological insights section
    # ------------------------------------------------------------------

    def _add_insights_section(self) -> None:
        """Add a colour-coded HTML section listing biological insights."""

        html_parts: List[str] = []

        for sample, idata in self.multiomics_integration.items():
            insights: List[Dict[str, Any]] = idata.get("insights", [])
            if not insights:
                continue

            html_parts.append(f"<h4>{sample}</h4>")
            html_parts.append('<ul class="multiomics-insights">')

            for insight in insights:
                level_str: str = (insight.get("level") or "INFO").upper()
                # The Rust serialiser may emit the enum variant name directly
                # (e.g. "Warning") or the as_str() value ("WARN").
                level_key = _normalise_level(level_str)
                colour = _LEVEL_COLOURS.get(level_key, "#6c757d")
                label = _LEVEL_LABELS.get(level_key, level_str.capitalize())
                modality = insight.get("modality", "")
                if isinstance(modality, dict):
                    modality = modality.get("modality", "")
                message = insight.get("message", "")
                html_parts.append(
                    f'<li style="border-left: 4px solid {colour}; padding: 4px 8px; '
                    f'margin-bottom: 6px;">'
                    f'<strong style="color:{colour}">[{label}]</strong> '
                    f"<em>{modality}</em> — {message}"
                    f"</li>"
                )

            html_parts.append("</ul>")

        if not html_parts:
            return

        html = (
            '<style>'
            '.multiomics-insights { list-style: none; padding-left: 0; }'
            '</style>\n'
            + "\n".join(html_parts)
        )

        self.add_section(
            name="Biological Insights",
            anchor="multiomics-insights",
            description=(
                "Plain-English findings generated by the Multiomics insight engine. "
                "Insights are colour-coded by severity: "
                '<span style="color:#28a745"><b>Info</b></span>, '
                '<span style="color:#ffc107"><b>Warning</b></span>, '
                '<span style="color:#dc3545"><b>Critical</b></span>.'
            ),
            content=html,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _chrom_sort_key(chrom: str) -> tuple:
    """Return a sort key that places chr1–22 before chrX, chrY, chrM/MT."""
    c = chrom.lstrip("chr").upper()
    order = {"X": 23, "Y": 24, "M": 25, "MT": 25}
    if c in order:
        return (1, order[c], c)
    try:
        return (0, int(c), c)
    except ValueError:
        return (2, 99, c)


def _methylation_colour(index: int, total: int) -> str:
    """Generate an orange-gradient hex colour for methylation bar charts."""
    if total <= 1:
        return "#e6550d"
    ratio = index / (total - 1)
    # Interpolate from light orange (#fdae6b) to dark orange (#a63603)
    r = int(0xFD + ratio * (0xA6 - 0xFD))
    g = int(0xAE + ratio * (0x36 - 0xAE))
    b = int(0x6B + ratio * (0x03 - 0x6B))
    return f"#{r:02x}{g:02x}{b:02x}"


def _normalise_level(raw: str) -> str:
    """Map Rust enum variant names and as_str() values to our dict keys."""
    mapping = {
        "INFO": "INFO",
        "INFO": "INFO",
        "WARNING": "WARN",
        "WARN": "WARN",
        "CRITICAL": "CRIT",
        "CRIT": "CRIT",
    }
    return mapping.get(raw.upper(), "INFO")
